import Vue from 'vue';
import Vuetify, {
  VLayout,
  VContent,
  VContainer,
  VForm,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VSpacer,
  VTextField,
  VToolbar,
  VToolbarTitle,
  VIcon,
  VTooltip,
  VBtn,
  VFlex,
  VApp,
  VSnackbar,
  VAppBar,
  VAppBarNavIcon,
  VSubheader,
  VAvatar,
  VImg,
  VList,
  VListGroup,
  VListItem,
  VListItemTitle,
  VListItemContent,
  VListItemAction,
  VNavigationDrawer,
  VDialog,
  VFadeTransition,
  VSlider,
  VDataTable,
  VMenu,
  VSwitch,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelHeader,
  VExpansionPanelContent,
  VProgressCircular,
} from 'vuetify/lib';

Vue.use(Vuetify, {
  components: {
    VLayout,
    VContent,
    VContainer,
    VForm,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VSpacer,
    VTextField,
    VToolbar,
    VToolbarTitle,
    VIcon,
    VTooltip,
    VBtn,
    VFlex,
    VApp,
    VSnackbar,
    VAppBar,
    VAppBarNavIcon,
    VSubheader,
    VAvatar,
    VImg,
    VList,
    VListGroup,
    VListItem,
    VListItemTitle,
    VListItemContent,
    VListItemAction,
    VNavigationDrawer,
    VDialog,
    VFadeTransition,
    VSlider,
    VDataTable,
    VMenu,
    VSwitch,
    VExpansionPanel,
    VExpansionPanels,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VProgressCircular,
  },
});

const opts = {}

export default new Vuetify(opts);
